### ISSUE TITLE
Difference between ignore and allow_streaming in config

### ISSUE THREAD

**Issue by sudoAlphaX** [lazykern/mprisence#35]
What is the difference between ignore and allow_streaming in the config file?

**Comment by lazykern** [comment]
`ignore` means that the player will be ignored and will not be processed and show as a rich presence.
`allow_streaming` will allow the rich presence for the player that plays a media using http and https protocol.

**Comment by sudoAlphaX** [comment]
> player that plays a media using http and https protocol.

Could you please elaborate on what a player that plays media using http protocol?

**Comment by lazykern** [comment]
For example, MPV can play the media from a URL which uses `http://` or `https://` and, but if it plays from a file, the `file://` protocol will be used.
That was how I separated the streaming and non streaming media. 

Please correct me if I was wrong, thanks!

**Comment by sudoAlphaX** [comment]
That's a really useful feature.
On that note, I'd like to request for an improvement. Along with allow_streaming, allow mprisence to capture only streaming events.
Currently, it is only possible to capture file playback or all playback. I feel it would be helpful to capture only URL playback.

Thank you for the amazing project.

**Comment by lazykern** [comment]
Roger that, also, thank you for your contribution!
