### ISSUE TITLE
Journalctl spammed if discord is not open

### ISSUE THREAD

**Issue by Blackilykat** [lazykern/mprisence#38]
My journalctl is often flooded by mprisence if it's running while discord isn't. I have to filter mprisence out entirely to make the journal readable

**Comment by lazykern** [comment]
Hi, please update mprisence to version 0.5.1. According to https://github.com/lazykern/mprisence/commit/b9283fb149f1e6aa12ac5286ead3901fe19d2293, mprisence will now check Discord status before updating the rich presence, it won't keep logging out errors every time it tries to connect to Discord now.
